# Generated by Django 5.1.2 on 2024-10-23 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgorun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BS', 'battle scared'), ('WW', 'well_worn'), ('FT', 'field tested'), ('MW', 'minimal wear'), ('FN', 'factory new')], default='BS', max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skin',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='skin',
            name='quality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='csgorun.quality'),
        ),
    ]
