# Generated by Django 5.1.1 on 2024-10-23 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgorun', '0002_quality_alter_case_cost_alter_skin_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
