# Generated by Django 5.1.2 on 2024-10-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csgorun", "0003_user_last_login_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_id",
            field=models.CharField(default="unnique_login", max_length=50),
        ),
        migrations.CreateModel(
            name="OpenCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="csgorun.case"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="csgorun.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_sum", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("sub", "sub"), ("add", "add")],
                        default="sub",
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="csgorun.user"
                    ),
                ),
            ],
        ),
    ]
